-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th6 30, 2025 lúc 07:46 PM
-- Phiên bản máy phục vụ: 8.0.40
-- Phiên bản PHP: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `userphp`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `webnhac_baihat`
--

CREATE TABLE `webnhac_baihat` (
  `idBH` int NOT NULL,
  `TenBH` varchar(255) NOT NULL DEFAULT '',
  `LoiBH` text,
  `urlBH` varchar(255) NOT NULL DEFAULT '',
  `idCS` int NOT NULL,
  `NgayCapNhat` date NOT NULL DEFAULT '0000-00-00',
  `SoLanNghe` int NOT NULL DEFAULT '0',
  `idNS` int NOT NULL DEFAULT '0',
  `idTL` int NOT NULL DEFAULT '0',
  `SoLanDown` int NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;

--
-- Đang đổ dữ liệu cho bảng `webnhac_baihat`
--

INSERT INTO `webnhac_baihat` (`idBH`, `TenBH`, `LoiBH`, `urlBH`, `idCS`, `NgayCapNhat`, `SoLanNghe`, `idNS`, `idTL`, `SoLanDown`) VALUES
(1, 'Tiếng Gà Trưa', 'Về trong phố xưa tôi nằm <br />\r\nCó lần nghe tiếng ru bên vườn <br />\r\nChợt như xác thân không còn <br />\r\nVà cạnh tôi là đồng vắng <br />\r\n<br />\r\nVề trên phố cao nguyên ngồi <br />\r\nTiếng gà trưa gáy khan   bên đồi <br />\r\nChợt như phố kia không người <br />\r\nCòn lại tôi bước   hoài <br />\r\n<br />\r\nLòng ta có khi tựa như vắng ai <br />\r\nNhiều khi đã   vui cười nhiều khi đứng riêng ngoài <br />\r\nNhiều đêm muốn đi về con phố xa <br />\r\nNhiều đêm muốn quay về ngồi yên dưới mái nhà <br />\r\n<br />\r\nGiòng   sông trước kia tôi về <br />\r\nBỗng giờ đây đã khô không ngờ <br />\r\nLòng tôi có khi mơ hồ <br />\r\nTưởng mình đang là cơn gió <br />\r\n<br />\r\nVề chân núi thăm nấm mồ <br />\r\nGiữa đường trưa có tôi bơ   phờ <br />\r\nChợt tôi thấy thiên thu <br />\r\nLà một đường không bến bờ <br />\r\n', '2/TiengGaTrua.mp3', 4, '2008-07-01', 58, 2, 2, 110),
(2, 'Biển nhớ', '<p>Ngày mai em đi, biển nhớ tên em gọi về <br />\r\n  Gọi hồn liễu rủ lê   thê, gọi bờ cát trắng đêm khuya <br />\r\n  Ngày mai em đi, đồi núi nghiêng nghiêng đợi   chờ<br />\r\n  Sỏi đá trông em từng giờ, nghe buồn nhịp chân bơ vơ <br />\r\n  Ngày mai em đi,   biển nhớ em quay về nguồn <br />\r\n  Gọi trùng dương gió ngập hồn, bàn tay chắn gió mưa   sang <br />\r\n  Ngày mai em đi, thành phố mắt đêm đêm mờ <br />\r\n  Hồn lẽ nghiêng vai gọi   buồn, nghe ngoài biển động buồn hơn <br />\r\n  <br />\r\n  Hôm nào em về, bàn tay buông lối ngõ <br />\r\n  Đàn lên cung phím chờ sầu lên dây hoang vu <br />\r\n  Ngày mai em đi, biển nhớ tên   em gọi về <br />\r\n  Chiều sương ướt đẫm cơn mê <br />\r\n  Trời cao níu bước sơn khê <br />\r\n  <br />\r\n  Ngày mai em đi, cồn đá rêu phong rũ buồn <br />\r\n  Đèn phố nghe mưa tủi hồn,   nghe ngoài trời giăng mây luôn <br />\r\n  Ngày mai em đi, biển có bâng khuâng gọi thầm <br />\r\n  Ngày mưa tháng nắng còn buồn, bàn tay nghe ngóng tin sang <br />\r\n  Ngày mai em   đi, thành phố mắt đêm đèn vàng <br />\r\n  Nửa bóng xuân qua ngập ngừng, nghe trời gió   lộng mà thương </p>\r\n', '', 0, '2008-07-08', 4, 2, 2, 6),
(3, 'Cát bụi', 'Hạt bụi nào hóa kiếp thân tôi<br />\r\nĐể một mai vươn hình hài lớn dậy<br />\r\nÔi cát bụi   tuyệt vời!<br />\r\nMặt trời soi một kiếp rong chơi.<br />\r\nHạt bụi nào hóa kiếp thân   tôi,<br />\r\nĐể một mai tôi về làm cát bụi.<br />\r\nÔi cát bụi mệt nhoài!<br />\r\nTiếng động   nào gõ nhịp không nguôi.<br />\r\n<br />\r\nBao nhiêu năm làm kiếp con người,<br />\r\nChợt một   chiều tóc trắng như vôi<br />\r\nLá úa trên cao rụng đầy<br />\r\nCho trăm năm vào chết một   ngày.<br />\r\n<br />\r\nMặt trời nào soi sáng tim tôi<br />\r\nĐể tình yêu xay mòn thành đá   cuội<br />\r\nXin úp mặt bùi ngùi<br />\r\nTừng ngày qua mỏi ngóng tin vui.<br />\r\nCụm rừng nào   lá xác xơ cây<br />\r\nTừ vực sâu nghe lời mời đã dậy<br />\r\nÔi cát bụi phận này<br />\r\nVết   mực nào xóa bỏ không hay.<br />\r\n', '2/CatBui.mp3', 4, '2008-09-01', 3, 2, 2, 9),
(4, 'Còn ai với ai', '<p>Không có em còn tôi với ai <br />\r\n  Không có em lạnh giá đường vui <br />\r\n  Không có em ngồi đứng nơi này <br />\r\n  Không có em còn ai có ai <br />\r\n  Em đã đi chìm   khuất đã theo, em đã như ngọn gió quạnh hiu <br />\r\n  Không có em đường cũ tiêu điều   em đã xa lìa trong nỗi đau <br />\r\n  Em đi biền biệt muôn trùng quá <br />\r\n  Từng cơn gió   và từng cơn gió <br />\r\n  Em đi gió lạnh bến xa bờ <br />\r\n  Từng nỗi nhớ trùng trùng nỗi   nhớ <br />\r\n  ... À ...a... ơi ...í .. a <br />\r\n  Không có em đường xa quá xa <br />\r\n  Em đã   thôi cười giữa chiều mưa <br />\r\n  Em đã đi đời có đâu ngờ , mang trái tim mùa xuân   héo khô <br />\r\n  Không có em buồn vui với ai <br />\r\n  Không có em lụa gấm nhạt phai <br />\r\n  Ai   đã chia người mãi xa người <br />\r\n  Ai giết đi tình đang lứa đôi </p>\r\n', '', 0, '2008-07-09', 1, 2, 2, 4),
(5, 'Diễm xưa', '<p>Mưa vẫn bay bay trên tầng tháp cổ <br />\r\n  Dài tay em mấy thuở mắt   xanh xao <br />\r\n  Nghe lá thu mưa reo mòn gót nhỏ <br />\r\n  Đường dài hun hút cho mắt thêm   sâu<br />\r\n  Mưa vẫn hay mưa trên hàng lá nhỏ <br />\r\n  Buổi chiều ngồi ngóng những chuyến   mưa qua <br />\r\n  Trên bước chân em âm thầm lá đổ <br />\r\n  Chợt hồn xanh buốt cho mình xót   xa <br />\r\n  Chiều nay còn mưa sao em không lại <br />\r\n  Nhớ mãi trong cơn đau vùi <br />\r\n  Làm   sao có nhau hằn lên nỗi đau <br />\r\n  Bước chân em xin về mau <br />\r\n  Mưa vẫn hay mưa cho   đời biến động <br />\r\n  Làm sao em biết bia đá không đau<br />\r\n  Xin hãy cho mưa qua miền   đất rộng <br />\r\n  Ngày sau sỏi đá cũng cần có nhau<br />\r\n  Mưa vẫn hay mưa cho đời biến   động <br />\r\n  Làm sao em nhớ những vết chim di<br />\r\n  Xin hãy cho mưa qua miền đất   rộng <br />\r\n  Để người phiêu lãng quên mình lãng du</p>\r\n', '2/DiemXua.mp3', 4, '2008-07-08', 5, 2, 2, 0),
(6, 'Để gió cuốn đi', 'Sống trong đời sống cần có một tấm lòng <br />\r\nĐể làm gì em biết không ?<br />\r\nĐể gió   cuốn đi , để gió cuốn đi <br />\r\nGió cuốn đi cho mây qua dòng sông <br />\r\nNgày vừa lên   hay đêm xuống mêng mông <br />\r\nÔi trái tim đang bay theo thời gian <br />\r\nLàm chiếc   bóng đi rao lời dối gian<br />\r\n \r\n<br />\r\nNhững khi chiều tới cần có một tiếng cười <br />\r\nĐể ngậm ngùi theo lá bay <br />\r\nRồi nước cuốn trôi , rồi nước cuốn trôi <br />\r\n<br />\r\nHãy nghiêng đời xuống nhìn hết một mối tình<br />\r\nChỉ lặng nhìn không nói   năng <br />\r\nĐể buốt trái tim để buốt trái tim<br />\r\nTrong trái tim con chim đau nằm   yên <br />\r\nNgủ dài lâu mang theo vết thương sâu <br />\r\nVà sớm mai chim bay đi triền   miên <br />\r\nVà tiếng hót vang trong trời gió lên <br />\r\n<br />\r\nHãy yêu ngày tới dù quá   mệt kiếp người <br />\r\nCòn cuộc đời ta cứ vui <br />\r\nDù vắng bóng ai , dù vắng bóng ai\r\n', '2/DeGioCuonDi-TruongThanh.mp3', 0, '2008-07-08', 0, 2, 2, 0),
(7, 'Hạ trắng', 'Gọi nắng trên vai em gầy đường xa áo bay <br />\r\nNắng qua mắt buồn , lòng hoa bướm   say <br />\r\nLối em đi về trời không có mây <br />\r\nĐường đi suốt mùa nắng lên thắp đầy <br />\r\n<br />\r\nGọi nắng cho cơn mê chiều nhiều hoa trắng bay <br />\r\nCho tay em dài gầy   thêm nắng mai <br />\r\nBước chân em về nào anh có hay <br />\r\nGọi em cho nắng chết trên   sông dài.<br />\r\n<br />\r\nThôi xin ơn đời trong cơn mê này gọi mùa thu tới <br />\r\nTôi đưa em   về chân em bước nhẹ trời buồn gió cao <br />\r\nĐời xin có nhau dài cho mãi sau nắng   không gọi sầu <br />\r\nÁo xưa dù nhàu cũng xin bạc đầu gọi mãi tên nhau <br />\r\n<br />\r\nGọi   nắng cho tóc em cài loài hoa nắng rơi<br />\r\nNắng đưa em về miền cao gió bay<br />\r\nÁo   em bây giờ mờ xa nẻo mây<br />\r\nGọi tên em mãi suốt cơn mê này.\r\n', '2/Hatrang-KhanhLy.mp3', 3, '2008-07-09', 2, 2, 2, 0),
(8, 'Hoa vàng mấy độ', '<p>Em đến bên đời hoa vàng một đóa<br />\r\n  một thoáng hương bay bên trời   phố hạ<br />\r\n  nào có ai hay ta gặp tình cờ<br />\r\n  nhưng là cơn gió em còn cứ mãi bay   đi</p>\r\n<p>em đến bên đời hoa vàng rực rỡ<br />\r\n  nào dễ chóng phai trong lòng   nỗi nhớ<br />\r\n  ngày tháng trôi qua cơn đau mịt mù</p>\r\n<p>xin cho bốn mùa<br />\r\n  đất trời lặng gió<br />\r\n  đường trần em đi<br />\r\n  hoa   vàng mấy độ<br />\r\n  những đường cỏ lá<br />\r\n  từng giọt sương thu<br />\r\n  yêu em thật thà</p>\r\n<p>em đến nơi này bao điều chưa nói<br />\r\n  lặng lẽ chia xa sao lòng quá   vội<br />\r\n  một cõi bao la ta về ngậm ngùi<br />\r\n  em cười đâu đó trong lòng phố xá đông   vui</p>\r\n<p>em đến nơi này vui buồn đi nhé<br />\r\n  đời sẽ trôi xuôi qua ghềnh qua   suối<br />\r\n  một vết thương thôi riêng cho một người</p>\r\n', '', 0, '2008-07-09', 0, 2, 2, 1),
(9, 'Một cõi đi về', '<p>Bao nhiêu năm rồi còn mãi ra đi <br />\r\n  Đi đâu loanh quanh cho đời   mỏi mệt <br />\r\n  Trên hai vai ta đôi vầng nhật nguyệt <br />\r\n  Rọi suốt trăm năm một cõi   đi về <br />\r\n  Lời nào của cây lời nào cỏ lạ <br />\r\n  Một chiều ngồi say một đời thật nhẹ   ngày qua <br />\r\n  Vừa tàn mùa xuân rồi tàn mùa hạ <br />\r\n  Một ngày đầu thu nghe chân ngựa   về chốn xa <br />\r\n  Mây che trên đầu và nắng trên vai <br />\r\n  Đôi chân ta đi sông còn ở   lại <br />\r\n  Con tinh yêu thương vô tình chợt gọi <br />\r\n  Lại thấy trong ta hiện bóng con   người <br />\r\n  Nghe mưa nơi nầy lại nhớ mưa xa <br />\r\n  Mưa bay trong ta bay từng hạt nhỏ <br />\r\n  Trăm năm vô biên chưa từng hội ngộ <br />\r\n  Chẳng biết nơi nao là chốn quê nhà <br />\r\n  Đường chạy vòng quanh một vòng tiều tụy <br />\r\n  Một bờ cỏ non một bờ mộng mị   ngày xưa <br />\r\n  Từng lời tà dương là lời mộ địa <br />\r\n  Từng lời bể sông nghe ra từ độ   suối khe <br />\r\n  Trong khi ta về lại nhớ ta đi <br />\r\n  Đi lên non cao đi về biển rộng <br />\r\n  Đôi tay nhân gian chưa từng độ lượng <br />\r\n  Ngọn gió hoang vu thổi suốt xuân   thì <br />\r\n  Hôm nay ta say ôm đời ngủ muộn <br />\r\n  Để sớm mai đây lại tiếc xuân thì</p>\r\n', '2/MotCoiDiVe.mp3', 0, '2008-07-10', 0, 2, 2, 0),
(10, 'Ru tình', '<div>Ru em đầu cơn   gió, em hong tóc bên hồ <br />\r\n  Khi sen hồng mới nở, nụ đời ôi thơm quá <br />\r\n  Ru em   tình khi nhớ, ru em tình lúc xa <br />\r\n  Ru cho bầy lá nhỏ, rụng đầy một mùa Thu <br />\r\n  <br />\r\n  Ru khi mùa mưa tới, ru em mãi yêu người <br />\r\n  Ru em hoài bé dại, một hồn   thơm cây trái <br />\r\n  Ru em chờ em nói, trên môi tình thoát thai <br />\r\n  Ru em ngồi yên   đấy, ru tình à ..ơi <br />\r\n  <br />\r\n  Ru người ngồi mãi cùng tôi <br />\r\n  Ru người ngồi mãi   cùng tôi <br />\r\n  <br />\r\n  Ru em hài nhung gấm, ru em gót sen hồng <br />\r\n  Ru bay tà áo rộng,   vượt tình tôi chấp cánh <br />\r\n  Ru trên đường em đến, xôn xao từng tiếng chim <br />\r\n  Ru   em là cánh nhạn, miệng ngọt hạt từ tâm <br />\r\n  <br />\r\n  Ru em tình như lá, trăm năm vẫn   quay về <br />\r\n  Môi em là đốm lửa, cuộc đời đâu biết thế <br />\r\n  Xin em còn đâu đó, cho   tôi còn tiếng ru <br />\r\n  Ru em ngồi yên đấy, tôi tìm cuộc tình cho</div>\r\n', '', 0, '2008-07-15', 0, 2, 2, 0),
(11, 'Tình xa', '', '', 0, '2008-07-16', 0, 2, 2, 1),
(12, 'Tình nhớ', '<p>Tình ngỡ đã quên đi như lòng cố lạnh lùng <br />\r\n  Người ngỡ đã xa   xăm bỗng về quá thênh thang <br />\r\n  Ôi áo xưa lồng lộng đã xô dạt trời chiều <br />\r\n  Như   từng cơn nước rộng xóa một ngày đìu hiu </p>\r\n<p>Tình ngỡ đã phôi pha nhưng tình vẫn còn đầy <br />\r\n  Người ngỡ đã đi   xa nhưng người vẫn quanh đây <br />\r\n  Những bước chân mềm mại đã đi vào đời người <br />\r\n  Như từng viên đá cuội rớt vào lòng biển khơi </p>\r\n<p>Khi cơn đau chưa dài thì tình như chút nắng <br />\r\n  Khi cơn đau lên   đầy thì tình đã mênh mông <br />\r\n  Một người về đỉnh cao, một người về vực sâu <br />\r\n  Để   cuộc tình chìm mau như bóng chim cuối đèo </p>\r\n<p>Tình ngỡ chết trong nhau nhưng tình vẫn rộn ràng <br />\r\n  Người ngỡ   đã quên lâu nhưng người vẫn bâng khuâng <br />\r\n  Những ngón tay ngại ngùng đã ru lại   tình gần <br />\r\n  Như ngoài khơi gió động hết cuộc đời lênh đênh </p>\r\n<p>Người ngỡ đã xa xưa nhưng người bỗng lại về <br />\r\n  Tình ngỡ sóng xa   đưa nhưng còn quá bao la <br />\r\n  Ôi trái tim phiền muộn đã vui lại một giờ <br />\r\n  Như   bờ xa nước cạn đã chìm vào cơn mưa. <br />\r\n</p>\r\n', '', 0, '2008-07-16', 0, 2, 2, 0),
(13, 'Ướt mi', '<p>Ngoài hiên mưa rơi rơi.Lòng ai như chơi vơi <br />\r\n  Người ơi nước   mắt hoen mi rồi <br />\r\n  Đừng khóc trong đêm mưa.Đừng than trong câu ca<br />\r\n  Buồn ơi   trong đêm thâu. Ôm ấp giùm ta nhé <br />\r\n  Người em thương mưa ngâu hay khóc sầu nhân   thế <br />\r\n  Tình ta đêm về có ấm từng cơn mơ em chưa.<br />\r\n  <br />\r\n  Mưa lạnh lùng rơi rớt   giữa đêm về<br />\r\n  Nghe não nề<br />\r\n  Mưa kéo dài lê thê những đêm khuya <br />\r\n  Lạnh ướt mi <br />\r\n  Ai còn nhìn mưa mãi rớt bên sông thêm lạnh lùng<br />\r\n  Ai còn buồn khi lá rớt   rơi trong một cuối đông<br />\r\n  <br />\r\n  Ngoài hiên mưa rơi rơi. Buồn dâng lên đôi môi <br />\r\n  Buồn đau hoen ướt mi ai rồi <br />\r\n  Buồn đi trong đêm khuya. Buồn rơi theo đêm   mưa <br />\r\n  Còn mưa trong đêm nay, lòng em buồn biết mấy <br />\r\n  Trời sao chưa thôi mưa   để mắt người em ấy <br />\r\n  Từ đây thôi mờ, nước mắt buồn mi em ngây thơ</p>\r\n', '', 0, '2008-07-16', 0, 2, 2, 0),
(14, 'Ru đời đi nhé', '<div>Có khi mưa   ngoài trời <br />\r\n  là giọt nước mắt em. <br />\r\n  Đã nương theo vào đời <br />\r\n  làm từng nỗi   ưu phiền... <br />\r\n  <br />\r\n  Ngoài phố mùa Đông <br />\r\n  đôi môi em là đốm lửa hồng. <br />\r\n  <br />\r\n  Ru đời đi nhé <br />\r\n  cho ta nương nhờ lúc thở than <br />\r\n  Chân đi nằng nặng <br />\r\n  hoang mang ta nghe tịch lặng <br />\r\n  rơi nhanh dưới khe im lìm. <br />\r\n  <br />\r\n  Ru đời   đi nhé <br />\r\n  ôi môi ngon này giữa trần gian. <br />\r\n  Ru từng chiếc bóng <br />\r\n  lênh đênh   vào giấc ngủ ngon. <br />\r\n  Cho tôi tay gối mong manh, <br />\r\n  cho tôi ôm lấy vai   thon</div>\r\n', '', 0, '2008-07-16', 0, 2, 2, 0),
(15, 'Ru ta ngậm ngùi', '<p>Môi nào hãy còn thơm, cho ta phơi cuộc tình.<br />\r\n  Tóc nào hãy còn   xanh, cho ta chút hồn nhiên<br />\r\n  Tim nào có bình yên, ta rêu rao đời mình<br />\r\n  Xin   người hãy gọi tên.</p>\r\n<p>Khi tình đã vội quên, tim lăn trên đường mòn<br />\r\n  Trên giọt máu   cuồng điên, con chim đứng lặng câm<br />\r\n  Khi về trong mùa đông, tay rong rêu muộn   màng.<br />\r\n  Thôi chờ những rạng đông..</p>\r\n<p>Xin chờ những rạng đông<br />\r\n  Đời sao im vắng<br />\r\n  Như đồng lúa gặt   xong<br />\r\n  Như rừng núi bỏ hoang<br />\r\n  Người về soi bóng mình.<br />\r\n  Giữa tường trắng   lặng câm.</p>\r\n<p>Có đường phố nào vui, cho ta qua một ngày<br />\r\n  Có sợi tóc nào bay,   trong trí nhớ nhỏ nhoi<br />\r\n  Không còn, không còn ai, ta trôi trong cuộc   đời<br />\r\n  Không chờ, không chờ aị</p>\r\n<p>Em về, hãy về đi, ta phiêu du một đờị<br />\r\n  Hương trầm có còn đây,   ta thắp nốt chiều nay<br />\r\n  Xin ngủ trong vòng nôi, ta ru ta ngậm ngùi,<br />\r\n  Xin ngủ   dưới vòm cây ... </p>\r\n', '', 0, '2008-07-17', 0, 2, 2, 0),
(16, 'Còn ai với ai', '', '', 0, '2008-07-15', 0, 2, 2, 0),
(17, 'Xin trả nợ người', 'Hai mươi năm xin trả nợ người <br />\r\n<br />\r\n<br />\r\nTrả nợ một thời em đã bỏ ai <br />\r\nHai   mươi năm xin trả nợ dài <br />\r\nTrả nợ một đời em đã phụ tôi <br />\r\n<br />\r\nEm phụ tôi một   đời bé dại <br />\r\nThơ dại ra đi không nhớ gì tôi <br />\r\n<br />\r\n<br />\r\nThơ dại ra đi quên hết   tình tôi <br />\r\n<br />\r\nHai mươi năm em trả lại rồi <br />\r\nTrả nợ một đời xa vắng vòng tay <br />\r\nHai mươi năm vơi cạn lại đầy <br />\r\nTrả nợ một thời môi <br />\r\n<br />\r\nvắng vòng môi. <br />\r\n<br />\r\nBao nhiêu năm em nợ ngọt ngào <br />\r\nTrả nợ một đời chưa hết tình sâu <br />\r\nBao nhiêu năm em nợ bạc đầu <br />\r\nTrả nợ một đời không hết tình đâu <br />\r\n<br />\r\n<br />\r\n<br />\r\nEm phụ tôi một đời bé dại <br />\r\nThơ dại ra đi không nhớ gì tôi <br />\r\nThơ dại ra đi quên hết tình tôi <br />\r\n<br />\r\nBao nhiêu năm bỗng lại nhiệm mầu <br />\r\nTrả nợ một <br />\r\n<br />\r\nlần quên hết tình đau <br />\r\nHai mươi năm vẫn là thuở nào <br />\r\nNợ lại lần này trong cõi đời nhau.\r\n', '', 0, '2008-07-21', 0, 2, 2, 0),
(18, 'Như cánh vạc bay', '<p>Nắng có hồng bằng đôi môi em <br />\r\n  Mưa có buồn bằng đôi mắt em <br />\r\n  Tóc em từng sợi nhỏ <br />\r\n  Rớt xuống đời làm sóng lênh đênh <br />\r\n  <br />\r\n  Gió sẽ mừng   vì tóc em bay <br />\r\n  Cho mây hờn ngủ trên trên vai <br />\r\n  Vai em gầy guộc nhỏ <br />\r\n  Như   cánh vạc về chốn xa xôi <br />\r\n  <br />\r\n  Nắng có còn hờn ghen môi em <br />\r\n  Mưa có còn buồn   trong mắt em <br />\r\n  Từ lúc đưa em về <br />\r\n  Là biết xa nghìn trùng <br />\r\n  <br />\r\n  Suối đón   từng bàn chân em qua <br />\r\n  Lá hát từ bàn tay thơm tho <br />\r\n  Lá khô vì đợi chờ <br />\r\n  Cũng như đời người mãi âm u <br />\r\n  <br />\r\n  Nơi em về ngày vui không em <br />\r\n  Nơi em   về trời xanh không em <br />\r\n  Ta nghe từng giọt lệ <br />\r\n  Rớt xuống thành hồ nước long   lanh</p>\r\n', '2/HongNhung-NhuCanhVacBay.mp3', 5, '2008-08-09', 1, 2, 2, 20),
(19, 'Ru em', '<div>Ru em ngủ   những đêm khuya<br />\r\n  Ru em ngủ tháng âm u<br />\r\n  Ru em cùng những u mê<br />\r\n  Ru em, ru em   dù đã chia xa<br />\r\n  <br />\r\n  Ru em về những đêm xưa<br />\r\n  Ru em phụ rẩy trong ta<br />\r\n  Ru em   quì gối vong nô<br />\r\n  Ru em, ru em vì dáng kiêu sa<br />\r\n  <br />\r\n  Ru từng ngọt bùi đã   qua<br />\r\n  Ru người lận đận héo khô<br />\r\n  Yêu em, yêu thêm tình phụ<br />\r\n  Yêu em lòng chợt   từ bi bất ngờ<br />\r\n  <br />\r\n  Ru em thèm khát xa hoa<br />\r\n  Ru em đầy những đam mê<br />\r\n  Ru em   tình nghĩa vu vơ<br />\r\n  Ru em, ru em chìm dưới phong ba<br />\r\n  <br />\r\n  Ru em mệt lã cơn   đau<br />\r\n  Ru em về giữa chiêm bao<br />\r\n  Ru em bồng bế con theo<br />\r\n  Ru em, ru em gầy yếu   hư hao<br />\r\n  <br />\r\n  Thôi rồi còn gì nữa đâu<br />\r\n  Đã tàn mộng mị khát khao<br />\r\n  Đôi khi con   tim hò hẹn<br />\r\n  Ngậm ngùi vì một ngày mưa bắt đầu ...<br />\r\n</div>\r\n', '2/HongNhung-RuEm.mp3', 5, '2008-09-04', 0, 2, 2, 0),
(20, 'Cho đời chút ơn', '<p>Hôm chợt thấy em đi về bên kia phố<br />\r\n  Trong lòng bỗng vui như   đời rất lạ<br />\r\n  Tôi tìm thấy tôi theo từng gót xa<br />\r\n  Làm lời hát ca trên đường   đi<br />\r\n  Tôi tìm thấy tôi như giọt nắng kia<br />\r\n  Làm hồng chút môi cho em nhờ</p>\r\n<p>Môi thiên đường hót chim khuyên<br />\r\n  Ôi tóc trầm ướp vai   thơm<br />\r\n  Ta nghe đời rất mênh mông<br />\r\n  Trong chân người bước chậm chậm.</p>\r\n<p>Hãy còn bước đi cho bình minh lên sớm<br />\r\n  Cho đời chút ơn biết tà   áo nọ<br />\r\n  Em là phấn thơm cho rừng chút hương<br />\r\n  Làm lời hát ca cho trần   gian<br />\r\n  Dưới đường phố kia có người nhớ em<br />\r\n  Nằm mộng suốt đêm trong thiên   đường</p>\r\n', '', 0, '2008-09-07', 0, 2, 2, 0),
(21, 'Cỏ xót xa đưa', '<div>Trên đời   người trổ nhánh hoang vu <br />\r\n  Trên ngày đi mọc cành lá mù <br />\r\n  Những tim đời đập   lời hoang phế. <br />\r\n  <br />\r\n  Dưới mặt trời ngồi hát hôn mê <br />\r\n  Dưới vòng nôi mọc từng   nấm mộ <br />\r\n  Dưới chân ngày cỏ xót xa đưa. <br />\r\n  <br />\r\n  Người đã đến và người sẽ về bên   kia núi <br />\r\n  Từng câu nói là từng cánh buồm giong cuối trời. <br />\r\n  Còn lại tiếng   cười khóc giữa đời. <br />\r\n  <br />\r\n  Dưới ngọn đèn một bóng chim qua <br />\r\n  Giữa đường đi   một người đứng gọi <br />\r\n  Có biết gì về ngày chưa tới. <br />\r\n  Những ngày ngồi rủ tóc   âm u <br />\r\n  Nghe tiền thần về chào bóng lạ <br />\r\n  Những mai hồng ngồi nhớ thiên   thu</div>\r\n', '2/HongNhung-CoXotXaDua.mp3', 5, '2008-09-05', 0, 2, 2, 0),
(22, 'Đêm thấy ta là thác đổ', '<p>Một đêm bước chân về gác nhỏ <br />\r\n  Chợt nhớ đóa hoa Tường Vi <br />\r\n  Bàn tay ngắt hoa từ phố nọ <br />\r\n  Giờ đây đã quên vườn xưa <br />\r\n  Một hôm bước qua   thành phố lạ <br />\r\n  Thành phố đã đi ngủ trưa <br />\r\n  Đời ta có khi tựa lá cỏ <br />\r\n  Ngồi   hát ca rất tự do <br />\r\n  Nhiều khi bỗng như trẻ nhớ nhà <br />\r\n  Từ những phố xưa tôi về <br />\r\n  Ngày xuân bước chân người rất nhẹ <br />\r\n  Mùa xuân đã qua bao giờ <br />\r\n  Nhiều đêm   thấy ta là thác đổ <br />\r\n  Tỉnh ra có khi còn nghe </p>\r\n<p>Một hôm bước chân về giữa chợ <br />\r\n  Chợt thấy vui như trẻ thơ <br />\r\n  Đời ta có khi là đóm lửa <br />\r\n  Một hôm nhóm trong vườn khuya <br />\r\n  Vườn khuya   đóa hoa nào mới nở <br />\r\n  Đời tôi có ai vừa qua <br />\r\n  Nhiều khi thấy trăm nghìn nấm   mộ <br />\r\n  Tôi nghĩ quanh đây hồ như <br />\r\n  Đời ta hết mang điều mới lạ <br />\r\n  Tôi đã sống   rất ơ hờ <br />\r\n  Lòng tôi có đôi lần khép cửa <br />\r\n  Rồi bên vết thương tôi quì <br />\r\n  Vì   em đã mang lời khấn nhỏ <br />\r\n  Bỏ tôi đứng bên đời kia </p>\r\n', '2/DemThayTalaThacDo.mp3', 0, '2008-07-16', 0, 2, 2, 0),
(23, 'Tuổi đá buồn', '<p>Trời còn làm mưa<br />\r\n  Mưa rơi mênh mang <br />\r\n  Từng ngón tay   buồn<br />\r\n  Em mang em mang <br />\r\n  Đi về giáo đường ngày chủ nhật buồn <br />\r\n  Còn ai còn   ai <br />\r\n  Đóa hoa hồng cài lên tóc mây <br />\r\n  Ôi đường phố dài <br />\r\n  Lời ru miệt mài <br />\r\n  Ngàn năm ngàn năm <br />\r\n  Ru em nồng nàn <br />\r\n  Ru em nồng nàn</p>\r\n<p>Trời còn làm mây <br />\r\n  Mây trôi lang thang <br />\r\n  Sợi tóc em bồng <br />\r\n  Trôi nhanh trôi nhanh <br />\r\n  Như giòng nước hiền <br />\r\n  Ngày chủ nhật buồn <br />\r\n  Còn   ai còn ai <br />\r\n  Đóa hoa hồng vùi quên trong tay <br />\r\n  Ôi đường phố dài <br />\r\n  Lời ru   miệt mài <br />\r\n  Ngàn năm ngàn năm <br />\r\n  Ru em giận hờn <br />\r\n  Ru em giận hờn </p>\r\n<p>Trời còn làm mưa <br />\r\n  Mưa rơi mưa rơi <br />\r\n  Từng phiến băng dài <br />\r\n  Trên hai tay xuôi <br />\r\n  Tuổi buồn em mang <br />\r\n  Đi trong hư vô <br />\r\n  Ngày qua hững   hờ <br />\r\n  Trời còn làm mưa <br />\r\n  Mưa rơi mưa rơi <br />\r\n  Từng phiến mây hồng <br />\r\n  Em mang   trên vai <br />\r\n  Tuổi buồn như lá <br />\r\n  Gió mãi cuốn đi <br />\r\n  Quay tận cuối trời </p>\r\n<p>Trời còn làm mưa <br />\r\n  Mưa rơi thênh thang <br />\r\n  Từng gót chân trần <br />\r\n  Em quên em quên <br />\r\n  Ôi miền giáo đường <br />\r\n  Ngày chủ nhật buồn <br />\r\n  Còn ai còn   ai <br />\r\n  Đóa hoa hồng tàn hôn lên môi <br />\r\n  Em gầy ngón dài <br />\r\n  Lời ru miệt mài <br />\r\n  Ngàn năm ngàn năm <br />\r\n  Ru em muộn phiền <br />\r\n  Ru em bạc lòng</p>\r\n', '', 0, '2008-07-15', 0, 2, 2, 0),
(24, 'Trong nỗi đau tình cờ', '<p>Tôi đã yêu em bao ngày nắng <br />\r\n  Tôi đã yêu em bao ngày mưa <br />\r\n  Yêu em bên đời lặng lẽ <br />\r\n  Tôi đã đưa em qua nhiều phố <br />\r\n  Những sáng mênh   mông tôi ngồi nhớ <br />\r\n  Yêu em trái tim thật thà <br />\r\n  <br />\r\n  Yêu đầy mùa nắng mùa mưa <br />\r\n  Yêu trong nỗi vui đợi chờ <br />\r\n  Đâu ngờ tình như lá úa <br />\r\n  Khiến tôi chia lìa   từng giấc mơ <br />\r\n  <br />\r\n  Tôi đã yêu em trong mùa gió <br />\r\n  Khi lá cây khô bay đầy ngõ <br />\r\n  Yêu em không cần vội vã <br />\r\n  Tôi đã yêu em như trẻ thơ <br />\r\n  Đâu biết đôi khi   có lìa xa <br />\r\n  Yêu trong nỗi đau tình cờ</p>\r\n', '', 0, '2008-07-14', 0, 2, 2, 0),
(25, 'Em đến từ nghìn xưa', '<div>Tôi vẫn nhìn   thấy em <br />\r\n  Giữa đám đông xa lạ <br />\r\n  Vì em mang trong mắt <br />\r\n  Nỗi yêu đời thiết   tha <br />\r\n  Tôi vẫn nhìn thấy em <br />\r\n  Giữa đám dông xa lạ <br />\r\n  Vì trong đôi mắt đó <br />\r\n  Có quê hương bạn bè <br />\r\n  <br />\r\n  Em đã đến giữa quê hương <br />\r\n  Có những nghìn năm   xưa <br />\r\n  Hoá thân em bây giờ <br />\r\n  Nên tôi vẫn nhìn thấy em <br />\r\n  Giữa đám đông xa lạ <br />\r\n  Vì em như chim trắng <br />\r\n  Giữa trống đồng bước ra <br />\r\n  Tôi vẫn nhìn thấy em <br />\r\n  Giữa đám đông xa lạ <br />\r\n  Vì em như hoa lá <br />\r\n  Giữa thiên nhiên hiền hòa</div>\r\n', '2/Emdentunghinxua-ThanhThuy.mp3', 0, '2008-09-04', 0, 2, 2, 0),
(26, 'Tôi ơi đừng tuyệt vọng', '', '', 0, '2008-09-06', 0, 2, 2, 0),
(27, 'Con mắt còn lại', 'Còn hai con mắt khóc người một con. <br />\r\nCòn hai con mắt một con khóc   người. <br />\r\nCon mắt còn lại nhìn cuộc đời tôi. <br />\r\nNhìn tôi lên cao nhìn tôi   xuống thấp. <br />\r\nCon mắt còn lại nhìn cuộc tình \r\nphai. <br />\r\nTình trong hai   tay một hôm biến mất. <br />\r\nCon mắt còn lại là con mắt ai. <br />\r\nCon mắt còn lại   nhìn tôi thở dài. <br />\r\nCòn hai con mắt khóc người một con \r\n<br />\r\n<br />\r\nCòn hai con   mắt một con khóc người. <br />\r\nCon mắt còn lại nhìn một thành hai <br />\r\nNhìn em yêu   thương nhìn em thú dữ. <br />\r\nCon mắt còn lại ngờ vực tình tôi. \r\n<br />\r\n<br />\r\nCuồng   điên yêu thương cuồng điên nỗi nhớ <br />\r\nCon mắt còn lại nhìn mây trắng bay <br />\r\nCon mắt còn lại nhìn tôi bùi ngùi. <br />\r\nCòn hai con mắt khóc người một con \r\n<br />\r\n<br />\r\nCòn hai con mắt một con khóc người. <br />\r\nCon mắt còn lại nhìn đời là   không <br />\r\nNhìn em hư vô nhìn em bóng nắng <br />\r\nCon mắt còn lại nhẹ nhàng từ tâm. <br />\r\nNhìn \r\nem ra đi lòng em xa vắng. <br />\r\nCon mắt còn lại là đêm tối tăm <br />\r\nCon mắt còn lại là đêm nồng nàn.\r\n', '2/Conmatconlai-TrinhCongSon.mp3', 7, '2008-09-05', 0, 2, 2, 0),
(28, 'Sóng về đâu', '<div>Biển sóng   biển sóng đừng xô tôi<br />\r\n  Đừng xô tôi ngã dưới chân người<br />\r\n  Biển sóng biển sóng   đừng xô nhau<br />\r\n  Ta xô biển lại sóng về đâu?<br />\r\n  <br />\r\n  Sóng bạc đầu và núi chìm   sâu<br />\r\n  Ta về đâu đó<br />\r\n  Về chốn nào mây phủ chiêm bao<br />\r\n  Cạn suối nguồn bốn bề   nương dâu<br />\r\n  Ta tìm em nơi đâu?<br />\r\n  <br />\r\n  Biển sóng biển đừng xô nhau<br />\r\n  Ta xô biển   lại sóng nằm đau<br />\r\n  Biển sóng biển sóng đừng xô tôi<br />\r\n  Đừng xô ngã tôi giữa tim   người.<br />\r\n  <br />\r\n  Biển sóng biển sóng đừng xô tôi<br />\r\n  Đừng cho tôi thấy hết tim   người<br />\r\n  Biển sóng biển sóng đừng xô nhau<br />\r\n  Ta xô biển lại sóng về   đâu?<br />\r\n  <br />\r\n  Giấc ngủ nào giường chiếu quạnh hiu<br />\r\n  Trăng mờ quê cũ<br />\r\n  Người đứng   chờ gió đông<br />\r\n  Vạt nắng vàng nhắc lời thiên thu<br />\r\n  Nhớ ngàn năm trôi   qua.<br />\r\n  <br />\r\n  Biển sóng biển sóng đừng trôi xa<br />\r\n  Bao năm chờ đợi sóng gần   ta<br />\r\n  Biển sóng biển sóng đừng âm u<br />\r\n  Đừng nuôi trong ấy trái tim   thù.<br />\r\n  <br />\r\n  Biển sóng... biển sóng... đừng xô nhau.</div>\r\n', '', 0, '2008-10-01', 0, 2, 2, 0),
(29, 'Em đi bỏ lại con đường', '<p>Bỏ mặc căn nhà, bỏ mặc tôi<br />\r\n  Bỏ mặc nơi đây, bỏ mặc người<br />\r\n  Bỏ   trăm năm sau, ngàn năm nữa<br />\r\n  Bỏ mặc tôi là, tôi là ai</p>\r\n<p>Em đi bỏ lại con đường<br />\r\n  Bờ xa cỏ dại, vô thường nhớ em<br />\r\n  Ra   đi,em đi bỏ lại dậm trường<br />\r\n  Ngàn dâu cố quạnh, muôn trùng nhớ thêm</p>\r\n<p>Bỏ mặc đêm dài, bỏ mặc tôi<br />\r\n  Bỏ mặc gian nan, bỏ mặc   người<br />\r\n  Bỏ xa xôi yêu và gần gũi<br />\r\n  Bỏ mặc tôi buồn giữa cuộc vui</p>\r\n<p>Bỏ mặc mưa về, bỏ chiều phai<br />\r\n  Bỏ mặc hư vô, bỏ ngậm ngùi<br />\r\n  Bỏ   đêm chưa qua, ngày chưa tới<br />\r\n  Bỏ mặc tay buồn không bàn tay</p>\r\n<p>Bỏ mặc vui buồn, bỏ mặc ai<br />\r\n  Bỏ mặc chân không, bỏ mặc   người<br />\r\n  Bỏ tôi hoang vu và nhỏ bé<br />\r\n  Bỏ mặc tôi ngồi giữa đời tôi</p>\r\n', '', 0, '2008-09-02', 0, 2, 2, 0),
(30, 'Bèo giạt mây trôi', 'Bèo dạt mây trôi, chốn xa xôi,<br />\r\nAnh   ơi, em vẫn đợi... í i ì... bèo dạt<br />\r\nMây í i ì... trôi,<br />\r\nchim sa, tang tính   tình... í i ì..., cao vời<br />\r\nNgậm một tin trông, hai tin đợi, ba bốn tin chờ<br />\r\nsao   chẳng thấy anh...<br />\r\n<br />\r\nMột mảnh trăng treo, suốt năm canh,<br />\r\nAnh ơi, trăng đã   ngã... a á à... ngang đầu<br />\r\nThương nhớ... ờ ơ... ai, sao rơi... đêm sắp tàn...   í i ì...<br />\r\ntrăng tà,<br />\r\nNgười ra đi có nhớ, (hay người xa có nhớ)<br />\r\nlà nhớ ai   ngồi trông cánh chim trời,<br />\r\nsao chẳng thấy anh...<br />\r\n<br />\r\nMòn mỏi thâu đêm,   suốt năm canh<br />\r\nAnh ơi, em vẫn đợi... í i ì... mỏi   mòn<br />\r\nThương nhớ... ờ ơ... ai<br />\r\nSao rơi, trăng sắp tàn .. í i ì... trăng   tà<br />\r\nCành tre đu trước ngõ<br />\r\nLà gió la đà em vẫn mong chờ, sao chẳng thấy   anh...<br />\r\n<br />\r\nThương nhớ.. ờ ơ... ai<br />\r\nSao rơi, trăng sắp tàn .. í i ì... trăng   tà<br />\r\nCành tre đu trước ngõ<br />\r\nLà gió la đà em vẫn mong chờ, sao chẳng thấy   anh....\r\n', '1/Beodatmaytroi-ThuHien.mp3', 11, '2008-09-01', 2, 1, 1, 42),
(31, 'Bông bí vàng', '<p>Bông bí vàng ngoài giàn, công em trồng anh không hái<br />\r\n  Trời sa   mưa bông kết trái, từ đó buồn, em buồn.<br />\r\n  Hum hum hum .... hum<br />\r\n  Trời mưa trên   khóm mía lau<br />\r\n  Trời rụng giọt mưa, xao xuyến xuyến xao<br />\r\n  Nhà em, dậu đổ bìm   leo<br />\r\n  Mà nhà anh mẹ cha rào mấy lượt rào<br />\r\n  Hỏi chớ con đường mòn nào, mà hai   đứa để gặp nhau<br />\r\n  Xui nên ta làm việc nhiều<br />\r\n  Kiếm đồng tiền dành mua sắm trầu   cau.<br />\r\n  Trâu cày ruộng cạn, trâu thở liền vô con trâu ơi thương dùm cuộc tình họ   đang cần có đôi bạn làm ăn<br />\r\n  Hum hum hum .... hum.<br />\r\n  Bây giờ trầu xanh vườn   trầu, cau trổ quày cau<br />\r\n  Mà mẹ cha không ngó xuống!<br />\r\n  Gió thổi năm non mà mẹ   cha chưa mát trong lòng<br />\r\n  Hái bông bí anh trồng anh đem luộc cầu xin.<br />\r\n  Bây   giờ trời mưa ngập ruộng, thương muộn còn thương<br />\r\n  Cuộc tình duyên trôi theo   dòng nước<br />\r\n  Bí trổ bông thơm một giàn bông không muốn hái bông nào<br />\r\n  Nhớ   thương nửa cuộc tình sao nghe ruột quặn đau .</p>\r\n', '1/Bongbivang-PhiNhung.mp3', 12, '2008-09-01', 0, 3, 1, 22),
(32, 'Bông điên điển', 'Hò ơ! Má ơi đừng gả con xa, <br />\r\nChim \r\nkêu vượn hú.... Hò ơ! <br />\r\nChim kêu   vượn hú, Biết đâu má tìm!&quot; <br />\r\n<br />\r\nEm đi lấy chồng về nơi xứ xa, <br />\r\nĐêm ru điệu   hát câu hò trên môi. <br />\r\nMiền Tây xanh sắc mây trời, <br />\r\nPhù sa nước nổi   người ơi đừng về! <br />\r\nVới màu điên điển say mê, <br />\r\nvàng trong ánh mắt vỗ về gót   chân. <br />\r\nTrót thương tình nghĩa vợ chồng, <br />\r\nNên bông  điên điển nở cho   lòng vấn vương. <br />\r\nTình thương em khó mà lường. <br />\r\n<br />\r\nChồng gần không lấy, em   lấy chồng xa, <br />\r\nGiờ đây nhớ mẹ thương cha, <br />\r\nCòn đâu mà thong  thả đi   về nhà thăm. <br />\r\nXa xăm nơi chốn bưng biền, <br />\r\nĂn bông mà điên điển, <br />\r\nNghiêng mình nhớ đât quê. <br />\r\nChồng xa em khó mà về. <br />\r\nHò ơ, ơi hò! Chồng   xa em  khó mà dzề <br />\r\n', '1/BongDiendien-PhiNhung.mp3', 12, '2008-09-01', 0, 7, 1, 17),
(33, 'Bông bưởi hoa cau', '<p>Tóc con dài mẹ cài bông hoa lý<br />\r\n  Mẹ lượm từng bông bưởi trắng   con gội đầu<br />\r\n  Mẹ kể chuyện xưa bông bưởi hoa cau<br />\r\n  Mẹ dạy từng câu hò lý ca   dao</p>\r\n<p>Nắng thu buồn nhuộm vàng ngõ trúc vắng<br />\r\n  Từng nhịp võng đưa mẹ   hát tiếng nghe buồn<br />\r\n  Chừng lưng lửng cơm mẹ gói mo cau<br />\r\n  Mẹ lên ruộng sâu gặt   hái nuôi con</p>\r\n<p>Con chợt nhớ vườn cau trước cửa<br />\r\n  Rồi con chợt nhớ vườn bưởi   sau hè<br />\r\n  Mẹ không còn, lượm từng bông bưởi trắng<br />\r\n  Cơn nhẹ gió bông bưởi rụng   đầy sân</p>\r\n<p>Con sẽ nhớ vườn cau ấy mãi<br />\r\n  Và con sẽ nhớ vườn bưởi trọn   đời<br />\r\n  Để khi nào mùa thu rụng lá<br />\r\n  Con lại nhớ bông bưởi rụng đầy sân ...</p>\r\n<p>Bông bưởi thơm vườn bưởi<br />\r\n  Đâu nữa để gội đầu<br />\r\n  Nhớ câu hò   điệu lý<br />\r\n  Mang giai điệu lời ru</p>\r\n<p>Đừng bay .... mà mòn mỏi sức chim<br />\r\n  Rồi bơ vơ cảnh la.<br />\r\n  Sợ   con tìm về cây xưa<br />\r\n  Sợ con tìm ... con tìm về cây xưa, .... cây xưa<br />\r\n  Sợ con   tìm ... con tìm về cây xưa, .... cây xưa...</p>\r\n', '1/BongBuoiHoaCau.mp3', 0, '2008-09-02', 0, 3, 1, 5),
(34, 'Lý con sáo', '', '1/Lyconsao-PhiNhung.mp3', 12, '2008-09-02', 0, 1, 1, 4),
(36, 'Đường về hai thôn', 'Đường về thôn \r\nem duyên dáng bên ven sông con thuyền xuôi mái <br />\r\nNhịp   cầu băng qua men lối đi quanh co, cỏ hoa nối dài <br />\r\nNhà em cuối xóm ghép đôi   mái tranh nâu trăng cài \r\ntrước sau <br />\r\nCó tằm mến thương dâu, Có trầu vấn   vương cau <br />\r\nvà đào tơ thơm ngát, ngát hương trinh ban đầu <br />\r\nĐường về thôn   anh con sáo ru êm êm trên đồng xanh lúa <br />\r\nNhịp cầu băng qua đưa lối   sân rêu xưa thắm hoa bốn mùa <br />\r\nNhà anh mái lá tháng năm vẫn chưa nghe duyên   tròn ước mơ <br />\r\nCó giàn mướp xanh lơ, Có hồ cá nên \r\nthơ <br />\r\nmà lòng quê   vẫn hát hát bao câu mong chờ <br />\r\nMỗi đêm trăng thanh ngà hội mùa lên tiếng ca   góp tay cần lao <br />\r\nÔi hai thôn giao đầu nhịp cầu tre bước chung \r\nêm vui   dường bao <br />\r\nTình ta lên men rồi còn chi ngăn cách lòng mà chưa trao giấc mơ   xuân cùng nhau <br />\r\nChày dâng lên trăng màu, bà con đang mong cầu \r\nrằng \r\nđôi ta sớm nên duyên ban đầu <br />\r\nĐường về hai thôn mai mốt đôi uyên ương   qua cầu soi bóng <br />\r\nNhủ thầm sông ơi gương nước chưa phôi pha ta còn vui hoài <br />\r\nTrời \r\nquê bát ngát sẽ trông thấy tương lai qua tình lứa đôi <br />\r\nLúa   đồng mãi xanh tươi, mướp cà thắm nơi nơi <br />\r\nvà vành môi trai gái góp bao câu ca   yêu đời <br />\r\nNhịp cầu \r\nđưa lối, chung bước hai thôn ta đón trăng về mừng   duyên quê\r\n', '1/Duongvehaithon-ThuHien.mp3', 11, '2008-09-03', 0, 8, 1, 1),
(37, 'Cát bụi', '', '4/catbui.mp3', 0, '2008-09-03', 0, 2, 4, 3),
(38, 'Tuổi đá buồn', '', '4/tuoida.mp3', 0, '2008-09-03', 0, 2, 4, 1),
(39, 'Nối vòng tay lớn', '', '4/noivong.mp3', 0, '2008-09-03', 0, 2, 4, 1),
(40, 'Hạ trắng', '', '4/hatrang.mp3', 0, '2008-09-03', 0, 2, 4, 0),
(41, 'Chiều một mình qua phố', '', '4/chieumot.mp3', 0, '2008-09-03', 0, 2, 4, 0),
(42, 'Huyền thoại mẹ', '', '4/huyenthoai.mp3', 0, '2008-09-03', 0, 2, 4, 0),
(43, 'Lời mẹ', '', '4/loime.mp3', 0, '2008-09-03', 0, 2, 4, 0),
(44, 'Mưa hồng', '', '4/muahong.mp3', 0, '2008-09-04', 0, 2, 4, 0),
(45, 'Quỳnh hương', '', '4/quynhhuong.mp3', 0, '2008-09-04', 0, 2, 4, 3),
(46, 'Hoa vàng mấy độ', '', '4/hoavang.mp3', 0, '2008-09-04', 0, 2, 4, 0),
(47, 'Mộng đẹp ngày xưa', '', '8/Mongdepngayxua.mp3', 0, '2008-09-05', 0, 1, 8, 19),
(48, 'Lòng mẹ', '', '8/Longme.mp3', 0, '2008-09-05', 0, 1, 8, 3),
(49, 'Làng tôi', '', '8/Langtoi.mp3', 0, '2008-09-05', 0, 1, 8, 2),
(50, 'Hương thầm', '', '8/Huongtham.mp3', 0, '2008-09-05', 0, 1, 8, 0),
(51, 'Xóm đêm', '', '8/Xomdem.mp3', 0, '2008-09-05', 0, 1, 8, 1),
(52, 'Lệ đá', '', '8/Leda.mp3', 0, '2008-09-05', 0, 1, 8, 0),
(53, 'Mười năm tình cũ', '', '8/Muoinamtinhcu.mp3', 0, '2008-09-05', 0, 1, 8, 3),
(54, 'Khúc tình ca xứ Huế', '', '8/KhuctinhcaxuHue.mp3', 0, '2008-09-05', 0, 1, 8, 0),
(55, 'Hình bóng quê nhà', '', '8/Hinhbongquenha.mp3', 0, '2008-09-05', 0, 1, 8, 1),
(56, 'Lý cây bông', '', '8/Lycaybong.mp3', 0, '2008-09-05', 0, 1, 8, 1),
(57, 'Lý mười thương', '', '8/Lymuoithuong.mp3', 0, '2008-09-06', 0, 1, 8, 0),
(58, 'Lý cái mơn', '', '8/Lycaimon.mp3', 0, '2008-09-06', 0, 1, 8, 0),
(59, 'Con đò dòng sông', '', '9/CONDODONGSONG(NGOCSON).MP3', 13, '2008-09-04', 0, 1, 9, 0),
(60, 'Con kênh xanh xanh', '<p>Con kênh xanh xanh những chiều êm ả lướt trôi <br />\r\n  Đêm đêm trăng   lên theo dòng buồm căng gió xuôi. <br />\r\n  Con kênh xanh xanh những mùa sen nở khắp   nơi <br />\r\n  Bao câu tơ duyên dạt dào tim ai thắm tươi </p>\r\n<p>Thuyền ai lướt qua hàng chuối với bờ kênh <br />\r\n  Thuyền ai lướt qua   bông lúa thướt tha <br />\r\n  Tiếng ai hò khoan vẳng đưa những câu tình ca <br />\r\n  Ngả   nghiêng hàng tràm vang hòa tiếng hò xa xa <br />\r\n  Chiến khu bừng vui ấm bao lòng dân   quê tôi <br />\r\n  Tiếng ai giã bàng nhịp nhàng như tiếng lòng tôi</p>\r\n<p>Con kênh xanh xanh những chiều êm ả nước trôi <br />\r\n  Ghi sâu nơi   tôi bao ngày chiến đấu nổi sôi <br />\r\n  Con kênh xanh ơi dập tàn chinh chiến khắp nơi <br />\r\n  Bên nhau ta xây trọn bài tình ca thắm tươi</p>\r\n', '9/Conkenhxanhxanh-NgoHuynh.mp3', 0, '2008-09-05', 0, 6, 9, 0),
(61, 'Còn thương rau đắng mọc sau hè', '<p>Nắng hạ đi<br />\r\n  Mây trôi lang thang cho hạ buồn<br />\r\n  Coi khói đốt   đồng, để ngậm ngùi chim nhớ lá rừng</p>\r\n<p>Ai biết mẹ buồn vui khi mẹ kêu cậu tới gần<br />\r\n  Biểu cậu ngồi mẹ   nhổ tóc sâu, hai chị em tóc bạc như nhau</p>\r\n<p>Đôi mắt cậu buồn hiu phiêu lưu<br />\r\n  Rong chơi những ngày đầu chừa   ba vá miếng dừa<br />\r\n  Đường mòn xưa, dãi nắng dầm mưa</p>\r\n<p>Ai cách xa cội nguồn,<br />\r\n  Ngồi một mình<br />\r\n  Nhớ lũy tre xanh dạo   quanh khung trời kỷ niệm<br />\r\n  Chợt thèm rau đắng nấu canh</p>\r\n<p>Xin được làm mây mà bay khắp nơi giang hồ<br />\r\n  Ghé chốn quê hương   xa rời từ cất bước ly hương<br />\r\n  Xin được làm gió dập dìu đưa điệu ca dao<br />\r\n  Chái   bếp hiên sau cũng ngọt ngào một lời cho nhau</p>\r\n<p>Xin sống lại tình yêu đơn sơ,<br />\r\n  Rong chơi những ngày đầu chừa   ba vá miếng dừa<br />\r\n  Đường mòn xưa, dãi nắng dầm mưa</p>\r\n<p>Xin nắng hạ thổi buồn để mình ngồi nhớ lũy tre xanh<br />\r\n  Dạo   quanh, khung trời kỷ niệm<br />\r\n  Chợt thèm rau đắng nấu canh   ... </p>\r\n', '9/Conthuongraudangmocsauhe-NhuQuynh.mp3', 14, '2008-09-06', 0, 3, 9, 0),
(62, 'Chùm bông hoa khế', '<p>Cây khế xưa em trồng bỏ một mình trước sân đình<br />\r\n  Nay nó vẫn   trổ bông<br />\r\n  Em có chăng một lần đứng lặng thầm trước sân thềm<br />\r\n  Nhìn qua nẻo cố   hương<br />\r\n  Anh vẫn sống một mình, một mình<br />\r\n  Một mái nhà tranh bụi tầm vông trước   ngõ<br />\r\n  Ngó qua sân đình đau lòng cơn gió<br />\r\n  Bông khế rụng, rụng mỗi hoàng   hôn</p>\r\n<p>Em về làm dâu nhà người lìa xa cố thổ<br />\r\n  Quên bụi chuối sau hè   bụi tre trước ngõ<br />\r\n  Tóc em rối bù gương lược biếng săm soi<br />\r\n  Gió vẫn mây trôi   ngồi buồn một mình</p>\r\n<p>Nơi quê xưa thung đường ương yếu nhớ thương mà nhìn<br />\r\n  Chỉ ngậm   ngùi<br />\r\n</p>\r\n', '9/CHUMBONGHOAKHE(HUONGLAN).MP3', 9, '2008-09-06', 0, 3, 9, 0),
(63, 'Chuyện tình Mimosa', '', '9/CHUYENTINHMIMOSA(NGOCSON).MP3', 13, '2008-09-06', 0, 1, 9, 0),
(64, 'Đám cưới trên đường quê', 'Ô ! ô ! sáng hôm nay trên quê hương tôi, <br />\r\nQuê hương xinh xinh quê hương hữu   tình, <br />\r\nQuê hương xinh xinh quê hương hòa bình, <br />\r\nĐường nở hoa trắng, xanh,   vàng, tím, <br />\r\nĐẹp làm sao bướm bay chập chờn. <br />\r\nĐàn chim non véo von ngọn   tre, <br />\r\nKhăn mầu son, áo mầu vàng, <br />\r\nƠi, bà con đến xem mùa cưới ! <br />\r\nChân   hài cong, tay dù hồng. <br />\r\nLâu thật lâu mới thấy được một ngày vui ! <br />\r\n<br />\r\nÔ !   ô ! sáng hôm nay quê tôi ra xem <br />\r\nCô dâu con con y trang mỹ miều. <br />\r\nCô dâu   non non dung nhan mặn mà. <br />\r\nChà ! nhà ai có ông rể quý. <br />\r\nChà ! nhà ai có cô   dâu hiền. <br />\r\nỒ ! ngộ thay có con lợn quay, <br />\r\nXôi đầy mâm, cau đầy buồng. <br />\r\nĐây nguồn vui hiếm hoi ngày cưới. <br />\r\nTrông thật hay, trông buồn cười. <br />\r\nRa mà xem mới thấy được cả niềm vui ! <br />\r\n<br />\r\nAnh anh ơi ! Người tình tôi ơi   ! <br />\r\nAnh anh ơi ! Xem người ta họ cưới nhau rồi ! <br />\r\nEm em ơi ! Người tình tôi   ơi ! <br />\r\nEm em ơi ! Chuyện chúng mình đã tính sao chưa ? <br />\r\nAnh anh ơi ! Người   tình tôi ơi ! <br />\r\nAnh anh ơi ! Xem người ta họ cưới nhau rồi ! <br />\r\nEm em ơi !   Người tình tôi ơi ! <br />\r\nEm em ơi ! Chuyện chúng mình cũng tính đi thôi !\r\n', '9/Damcuoitrenduongque-HuongLan.mp3', 9, '2008-09-06', 0, 9, 9, 0),
(65, 'Điệu buồn phương nam', '<p>Về phương Nam lắng nghe cung đàn <br />\r\n  thổn thức vọng dưới trăng   mơ màng <br />\r\n  Rồi theo sông Cửu Long nhớ nhung dâng tràn. <br />\r\n  Chợt thương con sáo   bay xa bầy <br />\r\n  sương khói buồn để lại lòng ai <br />\r\n  Con Sáo sang sông <br />\r\n  Sáo đã   xổ lồng <br />\r\n  Bay về Bạc Liêu, con sáo bay theo phương người <br />\r\n  Bay về Trà Vinh,   con sáo bay qua đời tôi. <br />\r\n  Câu hát ngân nga <br />\r\n  Tiếng tơ giao hòa <br />\r\n  Cháy lên   trong dạ muôn ngàn tâm sự <br />\r\n  Hát lên một lần để một đời xa nhau sáo ơi ! <br />\r\n  Đàn thiên thu đứt dây tơ rồi, theo sóng vàng cát lỡ sông bồi. <br />\r\n  Còn chi   nữa biển dâu đã bao đổi dời. <br />\r\n  Về phương Nam ngắm sông ngậm ngùi, <br />\r\n  Thương   những đời như lục bình trôi... </p>\r\n', '9/DIEUBUONPHUONGNAM(NGOCSON).MP3', 13, '2008-09-06', 0, 10, 9, 0),
(66, 'Dịu dàng sắc xuân', '<p>Nắng xuân ấm thơm môi hồng <br />\r\n  Gió xuân đến em bên em ngồi <br />\r\n  Cùng mùa xuân em hát câu tình ca <br />\r\n  <br />\r\n  Đóa cúc trắng bên hiên nhà <br />\r\n  Ngỡ   như dáng ai đang về <br />\r\n  Ngọt ngào hương xuân thắm trên bờ môi (vai) <br />\r\n  <br />\r\n  Nhịp   nhàng đàn chim én bay <br />\r\n  Ô kìa mùa về bao đắm say <br />\r\n  Một mùa xuân bao thắm   tươi! <br />\r\n  Quê hương với bao niềm vui! <br />\r\n  <br />\r\n  Rộn ràng đàn em bé thơ <br />\r\n  Tưng   bừng một mùa xuân mới sang <br />\r\n  Dịu dàng bao hương sắc xuân <br />\r\n  Hát cùng em khúc   tình ca <br />\r\n  <br />\r\n  Cánh mai thắm tươi xuân nồng <br />\r\n  Ấm đôi má em thêm hồng <br />\r\n  Cùng   mùa xuân em đến giữa đời vui ! <br />\r\n  <br />\r\n  Tiếng chim hót vui cho đời <br />\r\n  Tiếng em   hát thêm yêu người <br />\r\n  Đẹp mùa xuân đất nước trong lòng tôi ! <br />\r\n  <br />\r\n  Nhịp nhàng   đàn chim én bay <br />\r\n  Ô kìa mùa về bao đắm say <br />\r\n  Một mùa xuân bao thắm tươi! <br />\r\n  Quê hương với bao niềm vui! <br />\r\n  <br />\r\n  Rộn ràng đàn em bé thơ <br />\r\n  Tưng bừng một   mùa xuân mới sang <br />\r\n  Dịu dàng bao hương sắc xuân <br />\r\n  Hát cùng em khúc tình   ca </p>\r\n<p>Nắng xuân ấm thơm môi hồng <br />\r\n  Gió xuân đến em bên em ngồi <br />\r\n  Cùng mùa xuân em hát câu tình ca <br />\r\n  <br />\r\n  Đóa cúc trắng bên hiên nhà <br />\r\n  Ngỡ   như dáng ai đang về <br />\r\n  Ngọt ngào hương xuân thắm trên bờ môi (vai) <br />\r\n  <br />\r\n  Tiếng chim hót vui cho đời <br />\r\n  Tiếng em hát thêm yêu người <br />\r\n  Đẹp mùa   xuân đất nước trong lòng tôi</p>\r\n', '9/Diudangsacxuan-PhuongThanh.mp3', 15, '2008-09-06', 0, 11, 9, 0),
(67, 'Hồn Quê', 'Em theo anh qua những cánh đồng thơm lúa Việt nam <br />\r\nNơi bao năm xa cách tưởng   chừng hôm nay lớn dần <br />\r\nLòng buồn vời vợi xa xôi <br />\r\nGợi lại kỷ niệm khôn   nguôi <br />\r\nThương khói lam ban chiều và mái tranh thuở còn nằm nôi <br />\r\n<br />\r\nCây me   che bóng mát mỗi chiều ta đứng chờ nhau <br />\r\nDư âm xưa như ngỡ sống lại bên giây   phút đầu <br />\r\nLời nào ngọt ngào cho nhau <br />\r\nTình nào hò hẹn mai sau <br />\r\nThôi hãy   xem như cuộc đời ngủ quên chìm vào lắng sâu <br />\r\n<br />\r\nNhững năm tháng xa rời bạn   bè <br />\r\nNhớ thương quá cây phượng ngày hè <br />\r\nMùa nước lên điên điển trổ bông <br />\r\nBao nhiêu buồn vui ôm trọn vào lòng <br />\r\nLục bình trôi níu dòng đời trôi <br />\r\nGiọt lệ rơi thắm mặn bờ môi <br />\r\nUống chung nhau chén tình ngất trào để quên   thương đau. <br />\r\n<br />\r\nQuê hương em con gái áo bà ba gánh mạ non <br />\r\nCâu ca dao   trên lúa bốn ngàn năm hơn vẫn còn <br />\r\nCòn ruộng đồng còn thơm rơm <br />\r\nĐường về   nhà càng vui hơn <br />\r\nTa hãy đong cho thật tràn <br />\r\nChén tình đậm đà mến thương.\r\n', '9/HONQUE(HUONGLAN).MP3', 9, '2008-09-01', 0, 1, 9, 0),
(68, 'Mặt trời bé con', '<p>Ngoài kia có cô bé nhìn qua khe nghe tiếng đàn của tôi <br />\r\n  Ngoài   kia có chú bé trèo cành me mắt xoe tròn lắng nghe <br />\r\n  Đàn tôi hát câu gì mà sao   cô bé cười ngộ ghê <br />\r\n  Đàn tôi hát câu gì mà sao chú bé ngồi mơ màng <br />\r\n  Hạnh   phúc quá đơn sơ, đời tôi đâu có ngờ <br />\r\n  Từng đêm cô bé chờ như chờ từng giấc mơ <br />\r\n  <br />\r\n  Ngày xưa cũng như bé tuổi còn thơ tôi vẫn thường trộm nghe <br />\r\n  Nhà bên   có anh lính rời xa quê hay chơi đàn rất khuya <br />\r\n  Đàn anh đã cho tôi trời xanh   như ước mơ tuổi thơ <br />\r\n  Đàn anh đã cho tôi dòng sông mang cánh buồm khát vọng <br />\r\n  Tuổi thơ đã đi qua, giờ đây hát bên em, <br />\r\n  Từng đêm đứng quanh tôi những   mặt trời bé con <br />\r\n  <br />\r\n  Đàn anh đã cho tôi trời xanh như ước mơ tuổi thơ <br />\r\n  Đàn   anh đã cho tôi dòng sông mang cánh buồm khát vọng <br />\r\n  Tuổi thơ đã đi qua, giờ   đây hát bên em, <br />\r\n  Từng đêm đứng quanh tôi những mặt trời bé con <br />\r\n  <br />\r\n  Trời   mưa quá em ơi , bài ca ướt mất rồi , còn đâu . <br />\r\n  Trời mưa đến bao lâu , mà sao   em vẫn chờ vẫn đợi ... <br />\r\n  Hạnh phúc quá đơn sơ , đời tôi đâu có ngờ , <br />\r\n  Từng   đêm em vẫn chờ , vẫn chờ đợi dưới mưa ....</p>\r\n', '9/Mattroibecon-BangKieu.mp3', 16, '2008-09-06', 0, 5, 9, 0),
(69, 'Mưa ngâu', 'Giọt mưa <br />\r\nmưa ngâu mưa ngâu <br />\r\nbúp non trên cành thành lá biếc <br />\r\ngiọt mưa <br />\r\nmưa ngâu mưa ngâu <br />\r\ntròn xoe chiếc ô trên đầu <br />\r\n<br />\r\nNgày xưa đôi ta bên   nhau <br />\r\nchiếc ô xoe tròn là bóng lá <br />\r\nmong sao mưa thật lâu <br />\r\nđể cho đôi   lứa bên nhau <br />\r\n<br />\r\nNgày nay đôi ta xa nhau <br />\r\nvắng em anh nhìn từng góc phố <br />\r\ntừng đôi uyên ương bên nhau <br />\r\ntròn xoe chiếc ô trên đầu <br />\r\n<br />\r\nNgày nay   đôi ta xa nhau <br />\r\nlá xanh trên cành thành lá úa <br />\r\ntừng giọt mưa ngâu rớt bên   thềm <br />\r\ntình yêu đâu dễ lãng quên <br />\r\n<br />\r\nVà cơn mưa <br />\r\nmưa rồi sẽ tan đi trên   trời đầy nắng gió <br />\r\ngiọt mưa ngâu <br />\r\nhay là nước mắt ai nhớ nhau? <br />\r\n<br />\r\nChuyện tình yêu <br />\r\nnhư là những cơn mưa trong đời đầy nắng gió <br />\r\nđể   trên mi ai bây giờ <br />\r\nướt đẫm mưa ngâu\r\n', '9/Muangau(NgocAnh).mp3', 17, '2008-09-06', 0, 12, 9, 0),
(70, 'Tạm biệt chim én', '<p>Tạm biệt chim én xưa tạm biệt những giấc mơ <br />\r\n  Và giàn hoa tím   bên nhà ai nhớ mong <br />\r\n  Chào nụ hoa bé nhỏ dịu dàng trong đám cỏ <br />\r\n  Đợi chờ con   én những chiều xa rất xa <br />\r\n  ah ah ah ha ha ..... <br />\r\n  <br />\r\n  Em như chim bay xa   giữa đồng xanh quê hương bao la <br />\r\n  Tóc mùa xuân theo gió ru em ru em ru em bồng   bềnh <br />\r\n  Em như chim bay xa giữa đồng xanh quê hương bao la <br />\r\n  Tóc mùa xuân   theo gió ru em ru em ru em về quê hương <br />\r\n  <br />\r\n  Chiều nào trên phố xưa lặng nhìn   chim én bay <br />\r\n  Lòng thường mơ ước những đỉnh núi xa mờ <br />\r\n  Một ngày tiếng súng   về rồi người trai lên đường <br />\r\n  Để nhành hoa tím vẫy chào theo thiết tha <br />\r\n  <br />\r\n  Anh như chim bay xa những đàn chim bay trong phong ba <br />\r\n  Góc trời kia   chim én thương ai thương ai thương ai đợi chờ <br />\r\n  Anh như chim bay xa những đàn   chim bay trong phong ba <br />\r\n  Góc trời kia chim én thương ai thương ai thương ai   đợi chờ ai <br />\r\n  <br />\r\n  Một ngày tiếng súng ngưng, một người đi trở về <br />\r\n  tìm người   con gái trong mùa chim én bay <br />\r\n  bầu trời chim én liệng <br />\r\n  ngoài vườn hoa tím   nở <br />\r\n  mà người con gái đã về trên núi cao <br />\r\n  <br />\r\n  Ôi quê hương bao la tiếng đàn   tôi ngân xa ngân xa <br />\r\n  Hát về em cô gái yêu ai yêu ai đợi chờ ai <br />\r\n  Ôi quê   hương bao la tiếng đàn tôi ngân xa ngân xa <br />\r\n  Hát về em cô gái yêu ai yêu ai   đợi chờ ai </p>\r\n', '9/Tambietchimen-TranTien.mp3', 0, '2008-09-07', 0, 5, 9, 0),
(71, 'Tiếng vạc đêm sầu', '', '9/TIENGVACDEMSAU(NGOCSON).mp3', 13, '2008-09-07', 0, 1, 9, 0),
(72, 'Tiếng xưa', '<p>Hoàng hôn lá reo bên thềm <br />\r\n  Hoàng hôn tơi bời lá thu <br />\r\n  Sương   mờ ngậm ngùi xuân xanh <br />\r\n  Bâng khuâng phím loan vương tình <br />\r\n  <br />\r\n  Đâu bóng   trăng xưa mơ khúc nghê thường <br />\r\n  Phải tàn một thời liệt oanh xa đưa gió mây   lạnh lùng <br />\r\n  Chiều thu nhớ nhung vì đâu, thắm đôi giòng Châu <br />\r\n  Tiếc thay tại   sao đành lỡ làng man mác khói hương <br />\r\n  Bay dịu dàng như tóc mây vương <br />\r\n  Dáng   liễu mơ màng cung đàn nhỏ lệ Tầm Dương <br />\r\n  ai đó tri âm biết cùng. <br />\r\n  <br />\r\n  Hoàng   hôn gió sương lạnh lùng <br />\r\n  Hoàng hôn bao niềm nhớ nhung <br />\r\n  thiết tha đàn rung   tiếng tơ <br />\r\n  vấn vương trôi theo mây mờ <br />\r\n  đâu khúc cô liêu duyên dáng tiêu   điều <br />\r\n  dư âm chìm theo giòng Châu tràn lan sóng vương mạch sầu. <br />\r\n  Đàn ơi   thiết tha vì đâu, <br />\r\n  tiếng xưa trầm ngâm lắng rung đường tơ bao mơ màng <br />\r\n  Lưu   luyến hương thu thêm dịu dàng <br />\r\n  Ai có hay chăng Say khúc ưu tư, <br />\r\n  gió sương   chiều thu buồn mơ ai đó tri âm hững hờ. </p>\r\n', '9/TIENGXUA(HUONGLAN).MP3', 9, '2008-09-07', 0, 13, 9, 0),
(73, 'Tình thắm duyên quê', '<p>Tình nồng thắm xuyên qua bao mái tranh <br />\r\n  Ngọt ngào hương thơm   mái tóc xanh <br />\r\n  Những tình mặm mà là những tình đơn sơ <br />\r\n  Quê tôi vẫn đẹp đẹp   mấy tình ngây thơ <br />\r\n  Chiều làng quê say sưa trong tiếng ca <br />\r\n  Người làng quê   yêu bông lúa thiết tha <br />\r\n  Những mẹ già ngồi chom che lụa xóm dưới <br />\r\n  Rung rung   môi cười như tuổi còn đôi mươi <br />\r\n  Em ơi khoan hò khoan, trên sông con đò ngang <br />\r\n  Khoan ơi khoan hò, em về chăm lo <br />\r\n  Việc nhà thắm lúa, vun vườn cà liếp dứa <br />\r\n  Anh ơi khoan hò khoan, lúa chín tô mồ hôi <br />\r\n  Khoan hời khoan hò tới mùa đơm   bông <br />\r\n  Khơi ngàn lối sống, gặt nhanh ta gánh về <br />\r\n  Chiều tàn rơi trên đê nghe   tiếng ai <br />\r\n  Hẹn hò nhau vui duyên thắm gái trai <br />\r\n  Tiếng hò chơi vơi khi trăng   ngà lả lơi <br />\r\n  Đêm quê rộn ràng bao tiếng chày buông lơi <br />\r\n  Hàng dừa cao   nghiêng mơ soi bóng sông <br />\r\n  Mộng ngày mai say sưa những ước mong <br />\r\n  Gái miền   sông Hương hẹn trai miền Cửu Long <br />\r\n  Hai ta ước thề xây thắm tình duyên quê </p>\r\n<p>Em ơi khoan hò khoan, trên sông con đò ngang <br />\r\n  Khoan ơi khoan   hò, em về chăm lo <br />\r\n  Việc nhà thắm lúa, vun vườn cà liếp dứa <br />\r\n  Anh ơi khoan   hò khoan, lúa chín tô mồ hôi <br />\r\n  Khoan hời khoan hò tới mùa đơm bông <br />\r\n  Khơi   ngàn lối sống, gặt nhanh ta gánh về <br />\r\n  Chiều tàn rơi trên đê nghe tiếng ai <br />\r\n  Hẹn hò nhau vui duyên thắm gái trai <br />\r\n  Tiếng hò chơi vơi khi trăng ngà lả   lơi <br />\r\n  Đêm quê rộn ràng bao tiếng chày buông lơi <br />\r\n  Hàng dừa cao nghiêng mơ   soi bóng sông <br />\r\n  Mộng ngày mai say sưa những ước mong <br />\r\n  Gái miền sông Hương   hẹn trai miền Cửu Long <br />\r\n  Hai ta ước thề xây thắm tình duyên quê ... </p>\r\n', '9/Tinhthamduyenque-NhuQuynh.mp3', 14, '2008-09-07', 0, 14, 9, 0);
INSERT INTO `webnhac_baihat` (`idBH`, `TenBH`, `LoiBH`, `urlBH`, `idCS`, `NgayCapNhat`, `SoLanNghe`, `idNS`, `idTL`, `SoLanDown`) VALUES
(74, 'Thương quá Việt Nam', '<p>Em nghe gì không hỡi em <br />\r\n  Con chim nó hót vang đầu hè <br />\r\n  Em   thấy gì không hỡi em <br />\r\n  Con chim nó múa trên cành tre <br />\r\n  <br />\r\n  Hót đi chim, hót   đi chim <br />\r\n  Hót cho mặt trời hồng quê ta <br />\r\n  Hót đi chim, hót đi chim <br />\r\n  Hót   cho đời nhọc nhằn trôi xa <br />\r\n  <br />\r\n  Chim trên đồng chim trên non <br />\r\n  Chim tung   cánh xóa tan sương mù <br />\r\n  Chim trong hồn chim trong tim <br />\r\n  Ôi thương quá tiếng   chim việt Nam <br />\r\n  <br />\r\n</p>\r\n<p>Hót đi chim, hót đi chim <br />\r\n  Hót cho mặt trời hồng quê ta <br />\r\n  Hót đi chim, hót đi chim <br />\r\n  Hót cho đời nhọc nhằn trôi xa</p>\r\n<p><br />\r\n  Hoa cúc vàng trên sân anh <br />\r\n  Xinh như áo mới em ngày nào <br />\r\n  Hoa nắng hồng trên quê anh <br />\r\n  Xinh như má thắm em ngày xanh <br />\r\n  <br />\r\n  Nắng   lên đi, nắng lên đi <br />\r\n  Nắng lên hồng nụ cười quê em <br />\r\n  Nắng lên đi, nắng lên   đi <br />\r\n  Nắng lên hồng ruộng mạ xanh thêm <br />\r\n  <br />\r\n  Hoa tim người hoa yêu thương <br />\r\n  Hoa thơm ngát thế gian đêm buồn<br />\r\n  Hoa trên đồi hoa trên môi <br />\r\n  Ôi thương   quá cánh hoa việt Nam <br />\r\n  <br />\r\n</p>\r\n<p>Nắng lên đi, nắng lên đi <br />\r\n  Nắng lên hồng nụ cười quê em <br />\r\n  Nắng lên đi, nắng lên đi <br />\r\n  Nắng lên hồng ruộng mạ xanh thêm <br />\r\n  <br />\r\n  Trăng   sáng ngời trên môi hoa <br />\r\n  Trăng lên tiếng hát vui đêm già <br />\r\n  Trăng sáng ngời   trên non xa <br />\r\n  Trăng xua bóng tối trong hồn ta <br />\r\n  <br />\r\n  Sáng lên trăng, sáng lên   trăng <br />\r\n  Sáng cho ngưởi tìm về bên nhau <br />\r\n  Sáng lên trăng, sáng lên trăng <br />\r\n  Sáng cho tình người nở đêm sâu <br />\r\n  <br />\r\n  Trăng muôn đời, trăng muôn nơi <br />\r\n  Trăng đem bóng mát cho muôn người <br />\r\n  Trăng thanh bình, trăng yên vui <br />\r\n  Ôi   thương quá ánh trăng Việt Nam <br />\r\n</p>\r\n<p>Sáng lên trăng, sáng lên trăng <br />\r\n  Sáng cho ngưởi tìm về bên   nhau <br />\r\n  Sáng lên trăng, sáng lên trăng <br />\r\n  Sáng cho tình người nở đêm sâu</p>\r\n<p>Bao nhiêu đèn bao nhiêu hoa <br />\r\n  Bao nhiêu nến thắp lên trong hồn <br />\r\n  Yêu quê Mẹ, yêu quê Cha <br />\r\n  Yêu luôn những mái tranh làng xa <br />\r\n  <br />\r\n  Thắp   tim lên, thắp tim lên <br />\r\n  Thắp cho tình người dậy trong ta <br />\r\n  Thắp tim lên,   thắp tim lên <br />\r\n  Thắp cho mặt trời dậy trong ta <br />\r\n  <br />\r\n  Yêu thương người yêu   thương ta <br />\r\n  Yêu luôn những thú hoang rừng già <br />\r\n  Yêu bạn bè như yêu ta <br />\r\n  Ôi   thương quá trái tim Việt Nam </p>\r\n', '9/ThuongQuaVietNam-QuangLinh.mp3', 18, '2008-09-07', 0, 8, 9, 0),
(75, 'Trống cơm', '<p>Tình bằng có cái trống cơm <br />\r\n  Khen ai khéo vỗ <br />\r\n  Ố mấy bông mà   nên bông <br />\r\n  Ố mấy bông mà nên bông <br />\r\n  Một đàn tang tình con xít <br />\r\n  Một đàn   tang tình con xít <br />\r\n  Ố mấy lội, lội, lội sông <br />\r\n  Ố mấy đi tìm, em nhớ thương   ai <br />\r\n  Đôi con mắt ố mấy lim dim <br />\r\n  Đôi con mắt ố mấy lim dim <br />\r\n  Một bầy tang   tình con nhện <br />\r\n  Ô ố ô ô mấy giăng tơ <br />\r\n  Giăng tơ ô mấy đi tìm, em nhớ thương   ai <br />\r\n  Duyên nợ khách tang bồng <br />\r\n  Duyên nợ khách tang bồng.</p>\r\n', '9/Trongcom-NhuQuynh.mp3', 14, '2008-09-07', 0, 1, 9, 0),
(76, 'Trót dại', '', '9/Trotdai-NhuQuynh.mp3', 14, '2008-09-07', 0, 1, 9, 0),
(77, 'Lời cha', '', '10/LoiCha.mp3', 0, '2008-09-08', 0, 1, 10, 0),
(78, 'Lời Mẹ Ru', '', '10/LoiMeRu.mp3', 0, '2008-09-08', 0, 1, 10, 0),
(79, 'Lời ru nào mẹ đã ru con', '', '10/LoiRuNaoMeDaRuCon.mp3', 0, '2008-09-08', 0, 1, 10, 0),
(80, 'Lòng Mẹ', '', '10/LongMe_HuongLan.mp3', 9, '2008-09-08', 0, 1, 10, 0),
(81, 'Một đời cho con', '', '10/MotDoiChoCon_NguyenPhiHung.mp3', 20, '2008-09-09', 0, 1, 10, 0),
(82, 'Người cha', '', '10/NguoiCha_ThienKim.mp3', 21, '2008-09-09', 0, 1, 10, 0),
(83, 'Những ô cửa xanh', 'Bầy chim trắng vẫn thường qua những vụn bánh Cha   thả trên sân<br />\r\nTừng chậu hoa như bạn thân, yên lắng cùng Cha bên mùa   xuân<br />\r\nTừng trang sách Cha lật qua đưa con chạm đến bao vương quốc xa<br />\r\nNhững   câu chuyện theo con suốt đời, kể những giấc mơ bất đầu từ những ô cửa   xanh.<br />\r\n<br />\r\nCuộc sống đôi khi buồn tênh, năm tháng vụt qua không là cổ   tích<br />\r\nTình yêu đôi khi lìa xa, tích tắc thời gian quá mỏng manh<br />\r\nNhưng làm   sao có thể quên giây phút được Cha công kênh trên vai<br />\r\nNhững con đường mang   tên khát vọng mở những tương lai, bắt đầu từ những ô cửa xanh.<br />\r\n<br />\r\nCùng ngồi   bên con trong chiều mưa, cuốn phim ngày cũ nhắc lại năm xưa. <br />\r\nThấy quanh con   bao đổi thay và Cha cũng vậy, tóc bạc nhiều<br />\r\nNói với Mẹ và những người thân,   thấy nồng nàn tình Cha rất gần.<br />\r\n<br />\r\nCùng về bên Cha như ngày xưa, ngỡ như chỉ   có hai người trong mưa. <br />\r\nThấy bên con là tình yêu và quên tất cả bao vất vả. <br />\r\nBỗng thấy mình như năm mười bốn, đứng chập cững dưới hiên nhà Cha. <br />\r\nNghe   âm vang giọng nói hay là dòng sông đi xa hơn nữa<br />\r\nNhững giấc mơ tình yêu vỡ oà   đôi khi rất nhanh<br />\r\nHãy yêu cuộc sống như Cha hằng yêu, những giờ gần con và   những ô cửa xanh.<br />\r\n', '10/NhungOCuaXanh-NguyenPhiHung.mp3', 20, '2008-09-09', 0, 17, 10, 0),
(84, 'Ơn nghĩa sinh thành', '<p>Uống nước nhớ nguồn<br />\r\n  Làm con phải hiếu <br />\r\n  Ai ơi hãy nhớ năm   xưa<br />\r\n  Những ngày còn thơ<br />\r\n  Công ai nuôi dưỡng.</p>\r\n<p>Công đức sinh thành<br />\r\n  Người ơi đừng quên<br />\r\n  Công cha như núi   Thái Sơn<br />\r\n  Nghĩa mẹ như nước<br />\r\n  Trong nguồn chảy ra.</p>\r\n<p>Người ơi, làm người ở trên đời<br />\r\n  Nhớ công người sinh   dưỡng<br />\r\n  Đó mới là hiền nhân.<br />\r\n  Vì đâu, anh nên người tài ba<br />\r\n  Hãy nhớ công   sinh thành<br />\r\n  Vì ai, mà có ta?</p>\r\n<p>Uống nước nhớ nguồn<br />\r\n  Làm con phải hiếu<br />\r\n  Công cha như núi   Thái Sơn<br />\r\n  Nghĩa mẹ như nước<br />\r\n  Trong nguồn chảy ra... </p>\r\n', '10/OnNghiaSinhThanh.mp3', 0, '2008-09-09', 0, 13, 10, 0),
(85, 'Tình cha', '<div>Tình Cha ấm   áp như vầng Thái Dương <br />\r\n  Ngọt ngào như giòng nước tuôn đầu nguồn <br />\r\n  Suốt đời   vì con gian nan, <br />\r\n  Ân tình đậm sâu bao nhiêu, Cha hỡi Cha già dấu yêu <br />\r\n  <br />\r\n  Và con nhớ mãi những ngày tháng qua <br />\r\n  Kỷ niệm năm nào khó phai trong   lòng <br />\r\n  Nhớ hoài tuổi thơ bên Cha, gian khổ ngày đêm chăm lo <br />\r\n  Mong muốn con   được lớn khôn <br />\r\n  Còn nhớ những ngày ấy, những đêm trường giá lạnh <br />\r\n  Và Cha   nằm ôm con sưởi ấm những canh dài <br />\r\n  Nhè nhẹ hôn con và Cha khẽ nói: Này con   yêu ơi... <br />\r\n  Con hãy nhớ.. hãy nhớ... lời Cha sống cho nên người <br />\r\n  và con hãy   chớ bao giờ dối gian <br />\r\n  Nghèo thì cho sạch rách sao cho thơm! <br />\r\n  Những lời của   Cha năm xưa <br />\r\n  Con nguyện ghi sâu trong tim <br />\r\n  Cha hỡi Cha già dấu   yêu...</div>\r\n', '10/TinhCha_CheLinh.mp3', 23, '2008-09-09', 0, 1, 10, 0),
(86, 'Tình cha như biển trời', '', '10/TinhChaNhuBienTroi-HieuNgoc.mp3', 24, '2008-09-09', 0, 1, 10, 0),
(87, 'Tình Cha', 'Người là vầng Thái Dương<br />\r\nKhông như mẹ hiền trăng rằm dịu mát<br />\r\nNgười là ngọn   núi cao<br />\r\nÐứng che bão bùng cho rừng mãi xanh<br />\r\nTình người thật lớn lao<br />\r\nLấy   chi đo lường lòng Cha kính yêu<br />\r\nMặt Người giá băng, dấu trong tâm hồn chan   chứa yêu thương<br />\r\n<br />\r\nÐK.:<br />\r\nCha muốn cho con nên người, mà nghiêm khắc hơn mẹ   yêu<br />\r\nCha giúp cho con cuộc đời, đừng lạc bước chân trong màn đêm<br />\r\nNgười vui   lúc con thơ ngoan hiền<br />\r\nNgười thương lúc con thơ học hành<br />\r\nTình Cha mấy ai   nào biết đâu<br />\r\nTừng ngày lặng lẽ qua, biết bao êm đềm bên tình của Cha<br />\r\nLòng   bùi ngùi xót xa, nhớ xưa dại khờ vô tình lãng quên<br />\r\nNgười vì hạnh phúc   con,đắng cay muôn phần,chẵng than oán chi<br />\r\nTrọn đời nhớ ơn,chắp tay lạy Người,   Cha kính yêu ơi ...\r\n', '10/TinhCha-QuyLuan.mp3', 25, '2008-09-09', 0, 1, 10, 0),
(88, 'Tình Mẹ', '<p>Khẽ ngắt nụ hồng cài lên mái tóc xanh mẹ yêu <br />\r\n  Tóc rối một đời   vì năm tháng chở che đời con<br />\r\n  Khi thơ ấu con nào đâu có biết<br />\r\n  Mẹ lặng lẽ   trong ngàn nỗi muộn phiền <br />\r\n  Dù bao gió mưa tình mẹ vẫn thiết tha êm đềm </p>\r\n<p>Mẹ là những tiếng hát ấm áp ru con khi đông lạnh về <br />\r\n  Mẹ là   những ánh nắng lấp lánh đưa con đi trên đường quê<br />\r\n  Để con khôn lớn lên dang   rộng đôi vai<br />\r\n  Rồi đưa chân bước đi theo từng đêm vui. <br />\r\n  Mẹ vẫn tha thứ dù   cho con mang bao nhiêu lầm lỗi<br />\r\n  Mẹ đã có phút dấu nước mắt cho con thơ ngây nụ   cười <br />\r\n  Mẹ đã có những lúc thức trắng cho con bao đêm ngủ say <br />\r\n  Ngày con nâng   bó hoa xinh chào tương lai<br />\r\n  Mẹ cô đơn đứng bên hiên đầy mưa bay<br />\r\n  Trên mỗi   bước đi, xin mãi khắc ghi tình mẹ bao la biển trời</p>\r\n', '10/TinhMe_MyTam.mp3', 26, '2008-09-09', 0, 16, 10, 0),
(89, 'Tình mẹ', '', '10/TinhMe_TrangMyDung.mp3', 27, '2008-09-09', 0, 1, 10, 0),
(90, 'Ba ông thầy bói', '', '5/BaOngThayBoi-VanHuong.mp3', 0, '2008-09-09', 0, 1, 5, 0),
(91, 'Bông Lan', '', '5/BONGLANG.mp3', 0, '2008-09-09', 0, 1, 5, 0),
(92, 'Buồng cau quê ngoại', '', '5/BuongcauqueNgoai.mp3', 0, '2008-09-09', 0, 1, 5, 0),
(93, 'Con gái của mẹ', '', '5/CongaicuaMe.mp3', 0, '2008-09-10', 0, 1, 5, 0),
(94, 'Chuyến tàu về quê ngoại', '', '5/Chuyentauvequengoai.mp3', 0, '2008-09-10', 0, 1, 5, 0),
(97, 'Hoa trinh nữ', '', '5/Hoatrinhnu.mp3', 0, '2008-09-10', 0, 1, 5, 0),
(98, 'Không phải tại chúng mình', '', '5/Khongphaitaichungminh.mp3', 0, '2008-09-10', 0, 1, 5, 0),
(100, 'Lối cũ em về', '', '5/Loicuemve.mp3', 0, '2008-09-10', 0, 1, 5, 0),
(101, 'Lưu Bình Dương Lễ', '', '5/LuuBinhDuongLe.mp3', 0, '2008-09-10', 0, 1, 5, 0),
(102, 'Mai lỡ mình xa nhau', '', '5/Mailominhxanhau.mp3', 0, '2008-09-10', 0, 1, 5, 0),
(103, 'Tâm sự nàng Buram', '', '5/TamsunangBuram.mp3', 0, '2008-09-10', 0, 1, 5, 0),
(104, 'Tình nước', '', '5/TinhNuoc.mp3', 0, '2008-09-02', 0, 1, 5, 0);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `webnhac_baihat`
--
ALTER TABLE `webnhac_baihat`
  ADD PRIMARY KEY (`idBH`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `webnhac_baihat`
--
ALTER TABLE `webnhac_baihat`
  MODIFY `idBH` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=106;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
